import React, { useEffect, useState } from "react";
import Spacer from "../../components/UI/spacer/spacer";
import images from "../../constants/images";
import Image from "next/image";
import Head from "next/head";
import styles from "./aboutus.module.scss";
import { motion } from "framer-motion";
import axios from "axios";
import instance from "../../instanceAxios";
import useFormattedDate from "../../Hooks/useFormattedDate";

export default function index() {
    const mockData = [
        {
            id: 1,
            title: "NEWS1",
            descr: "newsDescritpion  newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion  ",
            date: "14/05/23",
        },
        {
            id: 2,
            title: "newsTiitle",
            descr: "newsDescritpion  newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion  ",
            date: "14/05/23",
        },
        {
            id: 3,
            title: "newsTiitle",
            descr: "newsDescritpion  newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion  ",
            date: "14/05/23",
        },
        {
            id: 4,
            title: "newsTiitle",
            descr: "newsDescritpion  newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion newsDescritpion  ",
            date: "14/05/23",
        },
    ];
    const developersData = [
        {
            position: "Frontend",
            name: "Олег Точеный",
            url: "https://t.me/RostovPaPaPRO",
        },
        {
            position: "Backend",
            name: "Константин Вернигоров",
            url: "https://github.com/vernicode",
        },
        {
            position: "QA",
            name: "Григорий Харчистов",
            url: "https://t.me/oneeightsevenwhat",
        },
        {
            position: "Project Manager",
            name: "Юрий Сухенко",
            url: "https://t.me/NoobchickBro",
        },
    ];

    const [news, setNews] = useState();
    const getNews = async () => {
        instance.get("/api/news.json").then(function (response) {
            console.log("news", response?.data);
            setNews(response?.data);
        });
    };
    useEffect(() => {
        getNews();
    }, []);

    return (
        <motion.div className={styles.wrapper}>
            <Head>
                <title>MY SPOT | О НАС</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta property="og:title" content="MY SPOT" key="title" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    rel="icon"
                    type="image/png"
                    sizes="144x144"
                    href="/icon.svg"
                />
                <script
                    src="https://api-maps.yandex.ru/3.0/?apikey=7066165f-a263-468f-9123-b4a3a32bdfb3&lang=ru_RU"
                    type="text/javascript"
                ></script>
            </Head>
            <div className="main__height main__wrapper">
                <Spacer size="xl" />
                <section className={styles.aboutUs}>
                    <div className={styles.aboutUs_text}>
                        <h1>О ПРОЕКТЕ</h1>
                        <h3>
                            Нашей целью было создать проект, который позволит
                            быстро находить места для катания, изучать новые
                            трюки и соревноваться друг с другом. Сайт
                            предназначен не только для новичков, но и для
                            опытных скейтеров.
                        </h3>
                    </div>
                    <Image src={images.logo} alt="logo" />
                </section>
                <Spacer size="xl" />

                <section className={styles.news_layout}>
                    <h1>НОВОСТИ —</h1>
                    <div className={styles.news_container}>
                        {news?.map((item) => (
                            <div className={styles.news}>
                                <h1>
                                    {useFormattedDate(item?.created_at).replace(
                                        /\./g,
                                        "/"
                                    )}
                                </h1>
                                <h2>{item?.title}</h2>
                                <p>{item?.description}</p>
                            </div>
                        ))}
                    </div>
                </section>

                <Spacer size="xl" />
                <section className={styles.developers}>
                    <h1>РАЗРАБОТЧИКИ —</h1>
                    <Spacer size="md" />
                    <div className={styles.developers_layout}>
                        {developersData.map((item) => (
                            <a
                                target="_blank"
                                href={item.url}
                                className={styles.developer_item}
                            >
                                <h1>{item?.position}</h1>
                                <h2>{item?.name}</h2>
                            </a>
                        ))}
                    </div>
                </section>
                <Spacer size="xl" />
            </div>
        </motion.div>
    );
}
